---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kvpurgpx/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R cgi=bin $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R json $DEPLOYPATH
    - /bin/cp -R master $DEPLOYPATH
    - /bin/cp -R META-INF $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp -R tpl $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R video $DEPLOYPATH
    - /bin/cp -R WEB-INF $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp body.html $DEPLOYPATH
    